version: "3"
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
          MYSQL_ROOT_PASSWORD: example
    volumes:
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
